### ISSUE TITLE
test case execution fail while using "nosetests"

### ISSUE THREAD

**Issue by dipika21** [hufman/flask_rdf#9]
`
#nosetests

EEE.......E
======================================================================
ERROR: Failure: AttributeError ("term 'birthday' not in namespace 'http://xmlns.com/foaf/0.1/'")
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/conda/envs/flask_restrdf/lib/python3.6/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/root/conda/envs/flask_restrdf/lib/python3.6/site-packages/nose/loader.py", line 413, in loadTestsFromName
    addr.filename, addr.module)
  File "/root/conda/envs/flask_restrdf/lib/python3.6/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/root/conda/envs/flask_restrdf/lib/python3.6/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/root/conda/envs/flask_restrdf/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/root/conda/envs/flask_restrdf/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jenkins/workspace/psl_flask_restrdf_rhel_7.6/flask_rdf/tests/test_bottle.py", line 16, in <module>
    graph = make_graph()
  File "/home/jenkins/workspace/psl_flask_restrdf_rhel_7.6/flask_rdf/tests/test_bottle.py", line 14, in make_graph
    graph.add((person, FOAF.birthday, Literal('2002-01-04', datatype=XSD.date)))
  File "/root/conda/envs/flask_restrdf/lib/python3.6/site-packages/rdflib/namespace.py", line 188, in __getattr__
    raise AttributeError(e)
AttributeError: "term 'birthday' not in namespace 'http://xmlns.com/foaf/0.1/'"
-------------------- >> begin captured logging << --------------------
rdflib: DEBUG: RDFLib Version: 5.0.0
--------------------- >> end captured logging << ---------------------`

**Comment by hufman** [comment]
Looks like `rdflib.namespace.FOAF` changed in https://github.com/RDFLib/rdflib/commit/384c60367 to be stricter, but the birthday attribute was missed. I'll submit a change.
Thanks for testing!

**Comment by dipika21** [comment]
hi @hufman - please let me know once done with changes.
